# Generated by Django 5.2.7 on 2025-11-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "male"), ("F", "female")],
                max_length=1,
                null=True,
            ),
        ),
    ]
