# Generated by Django 5.2.7 on 2025-10-27 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_rename_messsage_submitted_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submitted",
            options={"ordering": ["-created_time"]},
        ),
    ]
