# Generated by Django 5.2.7 on 2025-10-31 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0003_alter_submitted_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submitted",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
