"""
Django settings for my_site project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Application definition
INSTALLED_APPS = [
    'multi_captcha_admin',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "website.apps.WebsiteConfig",
    "home.apps.HomeConfig",
    "about.apps.AboutConfig",
    "contact.apps.ContactConfig",
    "blog.apps.BlogConfig",
    "elements.apps.ElementsConfig",
    "django.contrib.humanize",
    "django_extensions",
    "django.contrib.sites",
    "django.contrib.sitemaps",
    "robots",
    "debug_toolbar",
    "taggit",
    "django_summernote",
    "captcha",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "user_management.apps.UserManagementConfig",
    "django_otp",  # for 2fa
    "django_otp.plugins.otp_totp",  # for 2fa
    "django_otp.plugins.otp_static",  # for 2fa
    "allauth_2fa",
]


ROBOTS_USE_HOST = False
ROBOTS_USE_SITEMAP = False

# summernote config
SUMMERNOTE_THEME = "bs4"


MIDDLEWARE = ["django.middleware.security.SecurityMiddleware",
              "django.contrib.sessions.middleware.SessionMiddleware",
              "django.middleware.common.CommonMiddleware",
              "debug_toolbar.middleware.DebugToolbarMiddleware",
              "django.middleware.csrf.CsrfViewMiddleware",
              "django.contrib.auth.middleware.AuthenticationMiddleware",
              'django_otp.middleware.OTPMiddleware',
              "django.contrib.messages.middleware.MessageMiddleware",
              "django.middleware.clickjacking.XFrameOptionsMiddleware",
              "allauth.account.middleware.AccountMiddleware"
              ]

ROOT_URLCONF = "my_site.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "my_site.wsgi.application"


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
MEDIA_URL = "/media/"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# INTERNAL_IPS = [

#     "127.0.0.1",

# ]


# X_FRAME_OPTIONS = "SAMEORIGIN"

# captcha admin settings

MULTI_CAPTCHA_ADMIN = {
    'engine': 'simple-captcha',
}


# required for the decorator 'login_required()' to recognize the path of login

# LOGIN_URL = "user:login"


# to redirect to the main page with django.contrib.auth

LOGIN_REDIRECT_URL = "user:account_profile"


# allauth settings for login both with username or email

ACCOUNT_LOGIN_METHODS = {"email", "username"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "none"

# allauth settings for expiring the reset password link

PASSWORD_RESET_TIMEOUT = 600  # 10 minutes

# sending forget password when testing

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

# session not expire when browser is closed

# SESSION_EXPIRE_AT_BROWSER_CLOSE = False
# SESSION_COOKIE_AGE = 3600 * 24
# SESSION_SAVE_EVERY_REQUEST = True


# realy send forget password in practice

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = '#'
# EMAIL_HOST_PASSWORD = '#'
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# continue with goolge


SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '#',
            'secret': '#',
            'key': ''
        }
    }
}


# 2fa adapter

ACCOUNT_ADAPTER = 'allauth_2fa.adapter.OTPAdapter'


# adding another field for sign up

ACCOUNT_SIGNUP_FORM_CLASS = "user_management.forms.GenderSignUpForm"
AUTH_USER_MODEL = "user_management.CustomUser"
