# Generated by Django 5.2.7 on 2025-10-24 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="blog",
            new_name="post",
        ),
    ]
