# Generated by Django 5.2.7 on 2025-10-24 23:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_blog_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="text",
            new_name="content",
        ),
        migrations.AddField(
            model_name="post",
            name="counted_views",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="post",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="published_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="updated_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
