# Generated by Django 5.2.7 on 2025-10-31 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_category_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
