# Generated by Django 5.2.7 on 2025-11-02 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_comment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
