# Generated by Django 5.2.7 on 2025-11-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="image",
            field=models.ImageField(default="blog/dog.jpg", upload_to="blog/"),
        ),
    ]
