# Generated by Django 5.2.7 on 2025-11-02 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0015_comment_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_time"]},
        ),
    ]
